#!/usr/bin/env python3
"""Regenerate every moonmeow icon, vector drawable, banner and store image from one master.

Master: ``store-assets/meow/moonmeow.svg`` (the only hand-authored artwork). Everything this
script writes is generated -- never hand-edit a PNG or a generated vector drawable; change
the master (or the layout constants below) and re-run::

    bash store-assets/meow/build.sh

Most outputs REPLACE the content of upstream (Artemis) files under their existing names --
the manifest, ``ShortcutHelper``, ``TvChannelHelper`` and ``ExternalDisplayControlActivity``
reference those names, and renaming would be a code edit in each. The vector drawables in
``mipmap-anydpi-v26/`` and ``drawable-anydpi-v26/`` are new files that Android prefers over
the density PNGs on every supported device (minSdk 26), so the adaptive foreground, the
Android 13 themed-icon (``<monochrome>``) layer and the notification icon are all vectors.
Every replaced file is declared in ``docs/meow/TOUCHPOINTS.md`` (``green-brand``).

Tools: ``rsvg-convert`` (librsvg) for rasterising, Pillow for PNG packing. Mirrors meowerse
``packages/brand/scripts/build.sh``: green ``#00ff82`` mark on the dark ``#0d0d0d`` plate.
"""

import io
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

from PIL import Image

# Brand tokens -- meowerse packages/ui/src/styles/tokens.css, kept in sync by hand.
GREEN = "#00ff82"  # --mw-green
PLATE = "#0d0d0d"  # --surface-0 (dark)
INK = "#f2f2f2"  # --text-primary (dark)
INK_2 = "#a8a8a2"  # --text-secondary (dark)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MASTER = os.path.join(ROOT, "store-assets", "meow", "moonmeow.svg")
MAIN = os.path.join(ROOT, "app", "src", "main")
RES = os.path.join(MAIN, "res")
FASTLANE = os.path.join(ROOT, "fastlane", "metadata", "android", "en-US", "images")
SVG_NS = "http://www.w3.org/2000/svg"

#: launcher density buckets: (qualifier, legacy icon px, adaptive layer px)
DENSITIES = [("mdpi", 48, 108), ("hdpi", 72, 162), ("xhdpi", 96, 216),
             ("xxhdpi", 144, 324), ("xxxhdpi", 192, 432)]

#: Where the 256-unit glyph grid lands on the 108 dp adaptive-icon canvas: (offset, scale).
#: Adaptive icons are masked to at most the central 66 dp circle; both placements keep every
#: point of the glyph inside it (checked in ``selfcheck``).
MOON_LAYER = (25.0, 58.0 / 256)
PC_LAYER = (24.5, 59.0 / 256)


def load_master():
    """Return the id -> element map of the master SVG."""
    tree = ET.parse(MASTER)
    return {el.get("id"): el for el in tree.iter() if el.get("id")}


M = load_master()
PLATE_D = M["plate"].get("d")
GLYPH_T = M["glyph"].get("transform")
GLYPH_D = "".join(p.get("d") for p in M["glyph"].iter(f"{{{SVG_NS}}}path"))
PC_D = M["pc-glyph"].get("d")
WORDMARK_D, WORDMARK_ADV = M["wordmark"].get("d"), float(M["wordmark"].get("data-advance"))
TAGLINE_D, TAGLINE_ADV = M["tagline"].get("d"), float(M["tagline"].get("data-advance"))


def svg_doc(body, w=256, h=256, vw=None, vh=None):
    """Wrap ``body`` in a standalone SVG document."""
    vw, vh = vw or w, vh or h
    return (f'<svg xmlns="{SVG_NS}" width="{w}" height="{h}" viewBox="0 0 {vw} {vh}">'
            f"{body}</svg>\n")


def plated(d=GLYPH_D):
    """Plate + glyph (in the master's plate placement): a legacy/store icon."""
    return f'<path fill="{PLATE}" d="{PLATE_D}"/><path fill="{GREEN}" transform="{GLYPH_T}" d="{d}"/>'


def layer_svg(d, place, fill=GREEN):
    """The adaptive-icon foreground as SVG (108 unit canvas), for the density PNGs."""
    off, k = place
    return svg_doc(f'<path fill="{fill}" transform="translate({off} {off}) scale({k:.6f})" d="{d}"/>', 108, 108)


def vector_drawable(d, size_dp, viewport, fill, place=None, comment=""):
    """An Android VectorDrawable with one path, optionally placed by a group transform."""
    path = f'<path android:fillColor="{fill}" android:pathData="{d}"/>'
    if place:
        off, k = place
        path = (f'<group android:translateX="{off}" android:translateY="{off}" '
                f'android:scaleX="{k:.6f}" android:scaleY="{k:.6f}">\n        {path}\n    </group>')
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            f"<!-- GENERATED by store-assets/meow/build.sh from store-assets/meow/moonmeow.svg. "
            f"Do not edit by hand. {comment} -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size_dp}dp" android:height="{size_dp}dp"\n'
            f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">\n'
            f"    {path}\n</vector>\n")


def banner(w, h, mark, text_h, tagline=True):
    """Dark banner: moon icon on the left, wordmark (and tagline) to its right.

    ``text_h`` is an upper bound on the wordmark em size; it shrinks so that icon + gap +
    wordmark never take more than 84% of the banner width.
    """
    text_h = min(text_h, (0.84 * w - 1.22 * mark) / (WORDMARK_ADV / 100.0))
    s = text_h / 100.0
    ts = s * 0.42
    tw = max(WORDMARK_ADV * s, TAGLINE_ADV * ts if tagline else 0)
    gap = mark * 0.22
    mx = (w - (mark + gap + tw)) / 2
    my = (h - mark) / 2
    tx = mx + mark + gap
    if tagline:
        block = 0.72 * text_h + 0.30 * text_h + 0.72 * text_h * 0.42
        ty = h / 2 - block / 2 + 0.72 * text_h
        tag = (f'<path fill="{INK_2}" transform="translate({tx:.2f} {ty + 0.30 * text_h + 0.72 * text_h * 0.42:.2f}) '
               f'scale({ts:.5f})" d="{TAGLINE_D}"/>')
    else:
        ty, tag = h / 2 + 0.36 * text_h, ""
    body = (f'<rect width="{w}" height="{h}" fill="{PLATE}"/>'
            f'<g transform="translate({mx:.2f} {my:.2f}) scale({mark / 256.0:.5f})">{plated()}</g>'
            f'<path fill="{INK}" transform="translate({tx:.2f} {ty:.2f}) scale({s:.5f})" d="{WORDMARK_D}"/>' + tag)
    return svg_doc(body, w, h)


def render(svg, w, h=None):
    """Rasterise an SVG string at w x h with rsvg-convert."""
    h = h or w
    out = subprocess.run(["rsvg-convert", "-w", str(w), "-h", str(h), "-f", "png"],
                         input=svg.encode(), capture_output=True, check=True).stdout
    return Image.open(io.BytesIO(out)).convert("RGBA")


def write(path, data):
    """Write text or bytes; report the path relative to the repo."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w" if isinstance(data, str) else "wb") as fh:
        fh.write(data)
    print("  " + os.path.relpath(path, ROOT))


def save_png(img, path, opaque=False):
    buf = io.BytesIO()
    (img.convert("RGB") if opaque else img).save(buf, format="PNG", optimize=True)
    write(path, buf.getvalue())


MARKER = ("<!-- MEOW-TOUCH(green-brand): meowerse plate colour (surface-0, dark theme); "
          "value set by store-assets/meow/build.sh -->")


def set_color(path, name, value):
    """Rewrite one <color name=...> value in an upstream values file, leaving the rest.

    Upstream stores these files with CRLF line endings; ``newline=""`` keeps whatever the
    file uses, so the diff stays at exactly the value line plus the marker comment. The
    marker is (re)inserted above the colour if missing, e.g. after an upstream sync.
    """
    with open(path, newline="") as fh:
        src = fh.read()
    eol = "\r\n" if "\r\n" in src else "\n"
    new, n = re.subn(rf'(<color name="{name}">)[^<]*(</color>)', rf"\g<1>{value}\g<2>", src)
    if n != 1:
        sys.exit(f"{path}: expected exactly one <color name=\"{name}\">")
    if MARKER not in new:
        new = re.sub(rf'([ \t]*)(<color name="{name}">)', lambda m: f"{m.group(1)}{MARKER}{eol}{m.group(1)}{m.group(2)}", new)
    if new != src:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", newline="") as fh:
            fh.write(new)
        print("  " + os.path.relpath(path, ROOT))
    else:
        print("  " + os.path.relpath(path, ROOT) + " (unchanged)")


def selfcheck():
    """Fail loudly if a layer placement would let the launcher mask clip the glyph."""
    for name, d, place in (("moon", GLYPH_D, MOON_LAYER), ("pc", PC_D, PC_LAYER)):
        img = render(layer_svg(d, place, "#ffffff"), 432)
        px = img.load()
        c, lim = 216, 33 * 4  # 66 dp safe circle at xxxhdpi (4 px/dp)
        worst = max(((x - c) ** 2 + (y - c) ** 2) ** 0.5
                    for y in range(432) for x in range(432) if px[x, y][3] > 8)
        if worst > lim:
            sys.exit(f"{name} layer leaves the 66 dp safe zone ({worst / 4:.1f} dp > 33 dp)")


def main():
    if not shutil.which("rsvg-convert"):
        sys.exit("rsvg-convert (librsvg) not found")
    selfcheck()

    print("adaptive icons (vector, API 26+):")
    write(os.path.join(RES, "mipmap-anydpi-v26", "ic_launcher_foreground.xml"),
          vector_drawable(GLYPH_D, 108, 108, GREEN, MOON_LAYER,
                          "Adaptive foreground AND <monochrome> layer of ic_launcher."))
    write(os.path.join(RES, "mipmap-anydpi-v26", "ic_pc_scut_foreground.xml"),
          vector_drawable(PC_D, 108, 108, GREEN, PC_LAYER,
                          "Adaptive foreground AND <monochrome> layer of ic_pc_scut."))
    set_color(os.path.join(RES, "values", "ic_launcher_background.xml"), "ic_launcher_background", PLATE.upper())
    set_color(os.path.join(RES, "values", "ic_pc_scut_background.xml"), "ic_pc_scut_background", PLATE.upper())

    print("density PNGs (legacy + adaptive-layer fallbacks):")
    for q, legacy, layer in DENSITIES:
        d = os.path.join(RES, f"mipmap-{q}")
        save_png(render(svg_doc(plated()), legacy), os.path.join(d, "ic_launcher.png"))
        save_png(render(layer_svg(GLYPH_D, MOON_LAYER), layer), os.path.join(d, "ic_launcher_foreground.png"))
        save_png(render(svg_doc(plated(PC_D)), legacy), os.path.join(d, "ic_pc_scut.png"))
        save_png(render(layer_svg(PC_D, PC_LAYER), layer), os.path.join(d, "ic_pc_scut_foreground.png"))

    print("notification + TV channel:")
    # Status-bar icons are alpha-only: the system tints them, so white on transparent.
    write(os.path.join(RES, "drawable-anydpi-v26", "app_icon.xml"),
          vector_drawable(GLYPH_D, 24, 256, "#FFFFFFFF", comment="Notification small icon (alpha only)."))
    save_png(render(svg_doc(f'<path fill="#ffffff" d="{GLYPH_D}"/>'), 96), os.path.join(RES, "drawable", "app_icon.png"))
    # ic_channel.xml layers @drawable/ic_lime_layer over @color/ic_launcher_background for the
    # Android TV channel logo. An anydpi-v26 override wins over upstream's drawable/ copy on
    # every supported device, so the upstream file stays untouched.
    write(os.path.join(RES, "drawable-anydpi-v26", "ic_lime_layer.xml"),
          vector_drawable(GLYPH_D, 24, 256, GREEN, comment="TV channel logo glyph, see drawable/ic_channel.xml."))

    print("store / TV art:")
    # Play store icon: full-bleed square (Play applies its own corner mask), no alpha.
    full = svg_doc(f'<rect width="256" height="256" fill="{PLATE}"/>'
                   f'<path fill="{GREEN}" transform="{GLYPH_T}" d="{GLYPH_D}"/>')
    icon512 = render(full, 512)
    save_png(icon512, os.path.join(MAIN, "ic_launcher-web.png"), True)
    save_png(icon512, os.path.join(FASTLANE, "icon.png"), True)
    save_png(render(banner(320, 180, 104, 58), 320, 180), os.path.join(RES, "drawable-xhdpi", "atv_banner.png"), True)
    save_png(render(banner(732, 412, 236, 132), 732, 412), os.path.join(RES, "drawable-xhdpi", "ouya_icon.png"), True)
    save_png(render(banner(1280, 720, 400, 220), 1280, 720), os.path.join(FASTLANE, "tvBanner.png"), True)
    save_png(render(banner(1024, 500, 280, 150), 1024, 500), os.path.join(FASTLANE, "featureGraphic.png"), True)


if __name__ == "__main__":
    main()
